spring.application.name=encomiendas
# Conexion a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/BDD_FEEDEXX
spring.datasource.username=postgres
spring.datasource.password=232005

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Puerto del servidor (opcional)
server.port=8080

# API key de OpenRouteService (usada solo para calcular distancia/tiempo en Rutas)
ors.api.key=eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6IjdiNmQyZjcyZTJlMjQ5MTg5ZGIxZTk0MGM4ZWExYmQxIiwiaCI6Im11cm11cjY0In0=

